2017-09-15 15:46:54,805:     ERROR:Cannot div by zero
Traceback (most recent call last):
  File "exceptions1.py", line 16, in <module>
    1/0
ZeroDivisionError: division by zero
2017-09-15 15:47:31,440:     DEBUG:starting
2017-09-15 15:47:31,440:     ERROR:Cannot div by zero
Traceback (most recent call last):
  File "exceptions1.py", line 16, in <module>
    1/0
ZeroDivisionError: division by zero
